// 只需修改这个文件，即可替换第 2 至第 4 页的全部文案。
window.postcardContent = {
  2: {
    eyebrow: "MATCH DAY LIFE",
    title: "FOOTBALL",
    titleChinese: "足球",
    subtitle: "十年热爱，不止90分钟",
    description: "我是一个足球迷，也是10年的曼联死忠。初中的时候，常常半夜偷偷起来看球；到现在，我已经收集了不少曼联周边，包括球衣，卫衣和球员卡。胜负会改变，但这份热爱不会。",
    portraitCaption: "",
    factTitle: "看球档案",
    facts: ["支持球队： Machester United", "看球年限：10年+", "卡里克一声剑来，曼联重回榜首！", "梦想去一次老特拉福德球场🏟️"],
    captions: ["偶尔看看皇马的欧冠", "考完试后直奔世界杯酒吧（22年）", "马奎读秒绝杀，曼联逆转里昂", "Oh, dramatic game!", "b费点射，曼联3-0继续欧联征程"],
    photos: [
      { src: "images/football-profile.jpg", alt: "身穿曼联球衣眺望多伦多电视塔", position: "50% 50%", scale: 1 },
      { src: "images/Realmadrid.jpg", alt: "足球爱好照片 1", position: "50% 50%", scale: 1 },
      { src: "images/worldcup.jpg", alt: "足球爱好照片 2", position: "50% 50%", scale: 1 },
      { src: "images/Maguire.jpg", alt: "足球爱好照片 3", position: "50% 50%", scale: 1 },
      { src: "images/lyo.jpg", alt: "足球爱好照片 4", position: "50% 50%", scale: 1 },
      { src: "images/3-0.jpg", alt: "足球爱好照片 5", position: "50% 50%", scale: 1 },
    ],
  },
  3: {
    eyebrow: "KITCHEN LOG",
    title: "COOKING",
    titleChinese: "烹饪",
    subtitle: "Good Food, Good mood",
    description: "都说每一个留子都是一个好厨子，我也不例外。每次考试结束，或者完成一个大型项目后，我都会给自己做一顿大餐。对我来说，做饭不只是填饱肚子，也是放松、复盘和奖励自己的方式。",
    portraitCaption: "",
    factTitle: "厨房习惯",
    facts: ["菜系：北方菜、一锅炖", "时机：考试、项目结束后，周末", "从零开始做出一桌饭", "做饭很爽，洗锅太累👿"],
    captions: ["大家一起做的年夜饭", "‘三活一’的准备", "陕北烩菜，太香兰", "真的太喜欢烩菜了", "做饭必须配点绿菜"],
    photos: [
      { src: "images/WechatIMG1245.jpg", alt: "烹饪页个人照片", position: "50% 50%", scale: 1 },
      { src: "images/WechatIMG1230.jpg", alt: "烹饪爱好照片1", position: "50% 50%", scale: 1 },
      { src: "images/WechatIMG1239.jpg", alt: "烹饪爱好照片 2", position: "50% 50%", scale: 1 },
      { src: "images/WechatIMG1229.jpg", alt: "烹饪爱好照片 3", position: "50% 50%", scale: 1 },
      { src: "images/WechatIMG1232.jpg", alt: "烹饪爱好照片 4", position: "50% 50%", scale: 1 },
      { src: "images/WechatIMG1237.jpg", alt: "烹饪爱好照片 5", position: "50% 50%", scale: 1 },
    ],
  },
  4: {
    eyebrow: "ROAD NOTES",
    title: "SOLO TRIP",
    titleChinese: "独自旅行",
    subtitle: "一个人出发，也能拥有完整的风景",
    description: "大学以后，大家越来越难找到共同的时间旅行，但风景永远都在路上。Solo trip 让我可以按照自己的节奏出发，安静地观察一座城市、一段山路和每一场日落。",
    portraitCaption: "",
    factTitle: "旅行方式",
    facts: ["喜欢：山景、日落、散步", "随身物品：一个背包足以", "风景在路上，不等人的⛰️", "欲买桂花同载酒，终不似少年游"],
    captions: ["认真找角度拍草甸的全貌", "夜爬华山的日出", "黑神话的复活点", "老君山的彩灯很壮观", "马来西亚双子塔非常惊艳"],
    photos: [
      { src: "images/WechatIMG1247.jpg", alt: "旅行页个人照片", position: "50% 50%", scale: 1 },
      { src: "images/WechatIMG1227.jpg", alt: "旅行爱好照片 1", position: "50% 50%", scale: 1 },
      { src: "images/WechatIMG1226.jpg", alt: "旅行爱好照片 2", position: "50% 50%", scale: 1 },
      { src: "images/WechatIMG1235.jpg", alt: "旅行爱好照片 3", position: "50% 50%", scale: 1 },
      { src: "images/WechatIMG1221.jpg", alt: "旅行爱好照片 4", position: "50% 50%", scale: 1 },
      { src: "images/WechatIMG1219.jpg", alt: "旅行爱好照片 5", position: "50% 50%", scale: 1 },
    ],
  },
};
